
name: Build Go App and Installers

env:
  APP_NAME: bibletool
  CHROME_VERSION: 143.0.7499.169

on: 
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64

          - os: macos-14   # Apple Silicon runner
            arch: arm64
          
          - os: ubuntu-latest
            arch: amd64


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Enable CGO on macOS
        if: runner.os == 'macOS'
        run: echo "CGO_ENABLED=1" >> $GITHUB_ENV

      # Build binaries for each OS
      - name: Build Go binary
        shell: bash
        run: |
          set -e

          OUT="${APP_NAME}"

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            OUT="${APP_NAME}.exe"
            go build -ldflags "-H=windowsgui -s -w" -o "$OUT" .
          else
            go build -ldflags "-s -w" -o "${APP_NAME}-bin" .
          fi

      ############################################
      # WINDOWS: Download & Extract Chrome Headless Shell
      ############################################
      - name: Download & Extract Chrome Headless Shell (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -e

          ASSETS="assets"
          ZIP="chrome-headless-shell-win64.zip"
          TEMP="temp-chrome"

          # create assets folder
          mkdir -p "$ASSETS"

          # remove old files
          rm -f "$ZIP"
          rm -rf "$TEMP"

          # download zip
          curl -L -o "$ZIP" "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/win64/chrome-headless-shell-win64.zip"

          # unzip to temp
          unzip "$ZIP" -d "$TEMP"

          # move contents to assets directly (no subfolder)
          mv "$TEMP"/*/* "$ASSETS/"

          # cleanup
          rm -rf "$TEMP" "$ZIP"

          # make binaries writable
          chmod -R +w "$ASSETS"

      ############################################
      # WINDOWS: Build Inno Setup Installer
      ############################################
      - name: Install Inno Setup
        if: runner.os == 'Windows'
        run: choco install innosetup --yes

      - name: Build installer using ISS script
        if: runner.os == 'Windows'
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "InnoSetupConfigFile.iss"

      ############################################
      # MACOS: Download Chrome Headless Shell (arm64)
      ############################################
      - name: Download Chrome Headless Shell (macOS arm64)
        if: runner.os == 'macOS'
        run: |
          mkdir -p assets

          curl -L -o chrome-headless-shell-mac-arm64.zip \
            https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/mac-arm64/chrome-headless-shell-mac-arm64.zip

          unzip chrome-headless-shell-mac-arm64.zip
          mv chrome-headless-shell-mac-arm64 assets/chrome-headless-shell
          chmod +x assets/chrome-headless-shell/chrome-headless-shell
          
      ############################################
      # MACOS: Build .app bundle & .dmg
      ############################################
        
      - name: Make macOS .app bundle
        if: runner.os == 'macOS'
        run: |
          APP="Bibletool.app"

          mkdir -p $APP/Contents/MacOS
          mkdir -p $APP/Contents/Resources
          mkdir -p $APP/Contents/Resources/assets
          mkdir -p $APP/Contents/Resources/font
          
          # Binary
          cp bibletool-bin $APP/Contents/MacOS/bibletool
          chmod +x $APP/Contents/MacOS/bibletool

          # assets
          cp -R assets/chrome-headless-shell/* $APP/Contents/Resources/assets/

          # Info.plist
          cp mac/bibleTool/Info.plist $APP/Contents/

          # Resources
          cp -R bibles font cfg pics $APP/Contents/Resources/

          # copy env files go into MacOS
          if [[ -f "${GITHUB_WORKSPACE}/env" ]]; then
            cp "${GITHUB_WORKSPACE}/env" "$APP/Contents/Resources/"
            echo "env copied into app bundle"
          else
              echo "env not found, skipping"
          fi

          # copy icon files go into MacOS
          cp "${GITHUB_WORKSPACE}/pottershouse.icns" "$APP/Contents/Resources/"

      - name: Fix quarantine & sign macOS bibletool app
        if: runner.os == 'macOS'
        run: |
          xattr -dr com.apple.quarantine Bibletool.app
          codesign --force --deep --sign - Bibletool.app

      - name: Make macOS install .app bundle
        if: runner.os == 'macOS'
        run: |
          APP="installBibletool.app"

          mkdir -p $APP/Contents/MacOS
          mkdir -p $APP/Contents/Resources
          
          # Binary
          cp mac/installBibletool/installBibletool $APP/Contents/MacOS/installBibletool
          chmod +x $APP/Contents/MacOS/installBibletool

          # Resources
          cp -R Bibletool.app $APP/Contents/Resources/

          # Info.plist
          cp mac/installBibletool/Info.plist $APP/Contents/

          # copy icon files go into MacOS
          cp "${GITHUB_WORKSPACE}/pottershouse.icns" "$APP/Contents/Resources/"

      - name: Fix quarantine & sign macOS installBibletool app
        if: runner.os == 'macOS'
        run: |
          xattr -dr com.apple.quarantine installBibletool.app
          codesign --force --deep --sign - installBibletool.app

      - name: Create DMG
        if: runner.os == 'macOS'
        run: |
          DMG_NAME="installBibletool-macos-${{ matrix.arch }}.dmg"

          # create DMG
          hdiutil create -volname "installBibletool" \
          -srcfolder installBibletool.app \
          -ov -format UDZO \
          "$DMG_NAME"

      ############################################
      # LINUX: Download Chrome Headless Shell
      ############################################
      - name: Download Chrome Headless Shell (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p assets

          curl -L -o chrome-headless-shell-linux64.zip \
            https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/linux64/chrome-headless-shell-linux64.zip

          unzip chrome-headless-shell-linux64.zip
          mv chrome-headless-shell-linux64/chrome-headless-shell assets/
          chmod +x assets/chrome-headless-shell/chrome-headless-shell

      - name: Install AppImage tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libfuse2
          curl -L -o linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy

      ############################################
      # LINUX: Build AppImage
      ############################################
      - name: Build Linux AppImage
        if: runner.os == 'Linux'
        run: |
          APPDIR=AppDir

          mkdir -p $APPDIR/usr/bin
          mkdir -p $APPDIR/usr/share/applications
          mkdir -p $APPDIR/usr/share/icons/hicolor/256x256/apps
          mkdir -p $APPDIR/usr/share/bibletool

          # binary
          cp bibletool-bin $APPDIR/usr/bin/bibletool
          chmod +x $APPDIR/usr/bin/bibletool

          #copy .env
          cp .env $APPDIR/usr/bin/bibletool
          
          # assets
          cp -R assets $APPDIR/usr/share/bibletool/
          cp -R bibles font cfg pics $APPDIR/usr/share/bibletool/

          # desktop file
          cat > $APPDIR/usr/share/applications/bibletool.desktop <<EOF
          [Desktop Entry]
          Name=Bibletool
          Exec=bibletool
          Icon=bibletool
          Type=Application
          Categories=Utility;
          EOF

          # icon
          cp pottershouse.png $APPDIR/usr/share/icons/hicolor/256x256/apps/bibletool.png

          # AppRun
          cat > $APPDIR/AppRun <<EOF
          #!/bin/sh
          exec "\$(dirname "\$0")/usr/bin/bibletool"
          EOF
          chmod +x $APPDIR/AppRun

          ./linuxdeploy --appdir AppDir --output appimage
    

      ############################################
      # Upload Artifacts for each OS
      ############################################
      - name: Upload Windows artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Bibletool-Installer
          path: 'Output/Bibletool Setup.exe'

      - name: Upload macOS artifacts
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Bibletool-${{ matrix.arch }}
          path: |
            installBibletool-macos-${{ matrix.arch }}.dmg

      - name: Upload Linux artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Bibletool-AppImage
          path: '*.AppImage'




